[package]
name = "mmv"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive", "cargo"] }
glob = "0.3.1"
regex = "1.11.1"
assert_cmd = "2.0.16"
thiserror = "1.0.67"

[workspace]
